nombreproyecto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pepetube.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pepetube/urls.py
from django.urls import path
from . import views

app_name = 'pepetube'

urlpatterns = [
    path('', views.lista_videos, name='lista_videos'),
    path('ver/<int:pk>/', views.detalle_video, name='detalle_video'),
    path('crear/', views.crear_video, name='crear_video'),
    path('buscar/',views.buscar_videos, name='buscar_videos'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
]

pepetube/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Video(models.Model):
    usuario = models.ForeignKey(User,on_delete=models.CASCADE, null=True,blank=True)
    titulo = models.CharField(max_length=100)
    archivo_video = models.FileField(upload_to='videos/')
    archivo_imagen = models.ImageField(upload_to='imagenes/')
    fecha = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.titulo

pepetube/forms.py
from django import forms
from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['titulo', 'archivo_video','archivo_imagen']
    def __init__(self, *args, **kwargs):
        super(VideoForm, self).__init__(*args, **kwargs)
        self.fields['archivo_video'].widget.attrs['accept'] = 'video/mp4,video/x-m4v,video/*'

pepetube/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Video
from .forms import VideoForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

@login_required(login_url='pepetube:login')
def profile_view(request):
    return render(request, 'profile.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('pepetube:lista_videos')
    return render(request, 'login.html')

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pepetube:login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

@login_required(login_url='pepetube:login')
def logout_view(request):
    logout(request)
    return redirect('pepetube:login')

def lista_videos(request):
    videos = Video.objects.all()
    return render(request, 'lista_videos.html', {'videos': videos})

def buscar_videos(request):
    query = request.GET.get('query')
    if query:
        videos = Video.objects.filter(titulo__icontains=query)
    else:
        videos = Video.objects.all()
    return render(request, 'buscar_videos.html', {'videos': videos, 'query': query})

def detalle_video(request, pk):
    video = get_object_or_404(Video, pk=pk)
    return render(request, 'detalle_video.html', {'video': video})

@login_required(login_url='pepetube:login')
def crear_video(request):
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            video = form.save(commit=False)
            video.usuario = request.user
            video = form.save()
            return redirect('pepetube:detalle_video', pk=video.pk)
    else:
        form = VideoForm(initial={'usuario': request.user})
    return render(request, 'crear_video.html', {'form': form})

pepetube/templates/buscar_videos.html
{% extends 'encabezado.html' %}
{% block content %}
    {% for video in videos %}
    <div>
    <table>
    <tr>
    <td>
    <a href="{% url 'pepetube:detalle_video' video.pk %}">
    <img class="imagen" style="float: left;margin: 30px;margin-top: 0px;" class="buscado" src="{{video.archivo_imagen.url}}" width="550px" height="310"/>    
    <p style="margin-top: 40px;font-size: 25px;float: left;">{{ video.titulo }}</p>
    <p>{{ video.usuario }}</p>
    </a>
    </td>
    </tr>
    </table>
    </div>
    {% empty %}
    <h3 class="titulo">Ups, parece que no hay resultados!</h3>
    {% endfor %}

{% endblock content %}

pepetube/templates/crear_video.html
{% extends 'encabezado.html' %}
{% block content %}
<h1 style="margin-left: 30px;margin-bottom: 20px;">Subir Video!</h1>

<form class="subirvideo" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p style="margin-left:30px;">Titulo:</p>
    <input type="text" id="{{ form.titulo.id_for_label }}" name="{{ form.titulo.html_name }}" style="padding: 10px;margin-left: 30px;border-radius: 20px;background-color: rgb(20,20,20);border: solid 1px gray;padding-right: 200px;color: white;" autocomplete="off"><br><br>
    <input type="file" id="{{ form.archivo_video.id_for_label }}" name="{{ form.archivo_video.html_name }}" style="margin-left: 30px;border-radius: 20px;background-color: rgb(126, 126, 126);color: rgb(255, 255, 255);padding-right: 10px;margin-bottom: 30px;"><br>
    <input type="file" id="{{ form.archivo_imagen.id_for_label }}" name="{{ form.archivo_imagen.html_name }}" style="margin-left: 30px;border-radius: 20px;background-color: rgb(126, 126, 126);color: rgb(255, 255, 255);padding-right: 10px;margin-bottom: 30px;"><br>
    <button style="background-color: rgb(20,20,20);color: white;padding: 10px;border-radius: 20px;border: solid 1px gray;margin-left: 30px;" type="submit">Guardar</button>
</form>

{% endblock content %}

pepetube/templates/detalle_video.html
{% extends 'encabezado.html' %}
{% block content %}
    <video class="video" width="710" height="400" controls>
        <source src="{{ video.archivo_video.url }}" type="video/mp4">
        Tu navegador no soporta la reproducción de videos.
    </video>
    <h1 class="titulo">{{ video.titulo }}</h1>
    <h3 class="titulo"> {{video.usuario}} </h3>
    <p class="titulo">Subido el {{video.fecha}}</p>
{% endblock content %}

pepetube/templates/encabezado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pepetube</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">

</head>
<body>
    <div style="padding-bottom: 10px;padding-top: 10px;">

        <a href="{% url 'pepetube:lista_videos' %}">
        <img class="icono" src="{% static 'img/icon.png' %}" alt="Icono" width="30px"/>
        <h1 style="float: left;">PepeTube</h1>
        </a>

        {% if request.user.is_authenticated %}
        <a href="{% url 'pepetube:profile' %}">
        <p style="margin: 0; padding: 0;float: right;margin-right: 30px;margin-top: 10px;">
        {{ request.user.username }}
        </p>
        </a>
        {% else %}
        <a href="{% url 'pepetube:login' %}" style="float: right;">
        <img style="margin-right: 30px;margin-top: 10px;" class="login" src="{% static 'img/user.png' %}" width="30px"/>
        </a>
        {% endif %}
        <a href="{% url 'pepetube:crear_video' %}" style="float: right;">
        <img class="subir" src="{% static 'img/subir.png' %}" width="30px" />
        </a>

        <form class="buscador" method="GET" action="{% url 'pepetube:buscar_videos' %}">
            <input type="text" name="query" placeholder="Buscar..." autocomplete="off">
            <button type="submit">Buscar</button>
        </form>

    </div>
    <hr style="border-color: rgb(0, 0, 0);" >
    {% block content %}
    {% endblock content %}
</body>
</html>

pepetube/templates/lista_videos.html
{% extends 'encabezado.html' %}
{% block content %}
<div style="margin-top: 60px; display: flex; flex-wrap: wrap;">
    {% for video in videos %}
    <div style="width: 23%; padding: 10px;">
        <a href="{% url 'pepetube:detalle_video' video.pk %}">
            <img class="imagen" src="{{ video.archivo_imagen.url }}" width="300px" height="170px" />
            <p>{{ video.titulo }}</p>
            <p style="font-family: Arial; font-size: 12px;">Subido por {{ video.usuario }}</p>
            <p style="font-family: Arial; font-size: 12px;">{{video.fecha|date:"d-m-Y"}}</p>
        </a>
    </div>
    {% empty %}
    <p class="titulo">No hay videos disponibles.</p>
    {% endfor %}
</div>
{% endblock content %}

pepetube/templates/login.html
{% extends 'encabezado.html' %}
{% block content %}
<h2 class="titulo" style="margin-bottom: 20px;">Iniciar Sesión</h2>
<form method="post">
    {% csrf_token %}
    <input autocomplete="off" style="color: white;padding: 10px;border-radius: 20px;margin-left: 30px;background-color: rgb(30,30,30);border: solid 1px gray;margin-bottom: 30px;" placeholder="Usuario" type="text" id="username" name="username"><br>
    <input style="color:white;padding: 10px;border-radius: 20px;margin-left: 30px;background-color: rgb(30,30,30);border: solid 1px gray;margin-bottom: 30px;" placeholder="Contraseña" type="password" id="password" name="password"><br>
    <input style="padding: 10px;border-radius: 20px;margin-left: 30px;background-color: rgb(30,30,30);border: solid 1px gray;margin-bottom: 30px;color: white;" type="submit" value="Entrar">
</form>
<p class="titulo">No tienes una cuenta? <a href="{% url 'pepetube:register' %}" style="color: rgb(179, 179, 179);" >Regístrate</a></p>
{% endblock content %}

pepetube/templates/logout.html
<h2>Has cerrado sesión con éxito.</h2>
    <p><a href="{% url 'pepetube:login' %}">Login nuevamente</a></p>

pepetube/templates/profile.html
{% extends 'encabezado.html' %}
{% block content %}
<h2 class="titulo">Tu perfil</h2>
<br>
<p class="titulo" style="margin-bottom: 40px;" >Nombre de usuario: {{ request.user.username }}</p>

<a href="{% url 'pepetube:logout' %}"><p style="margin-left: 30px;padding: 10px;display: inline-block;background-color: rgb(60,60,60);border-radius: 30px;">Cerrar Sesión</p></a>
{% endblock content %}

pepetube/templates/register.html
{% extends 'encabezado.html' %}
{% block content %}
<h2 class="titulo" style="margin-bottom: 20px;">Registro</h2>
    <form method="post">
        {% csrf_token %}
        <label class="titulo" for="id_username">Nombre de usuario:</label><br>
        <input autocomplete="off" style="color:white;margin-top:10px;padding: 10px;border-radius: 20px;margin-left: 30px;background-color: rgb(30,30,30);border: solid 1px gray;margin-bottom: 30px;" type="text" id="id_username" name="username"><br>
        <label class="titulo" for="id_password1">Contraseña:</label><br>
        <input style="color:white;margin-top:10px;padding: 10px;border-radius: 20px;margin-left: 30px;background-color: rgb(30,30,30);border: solid 1px gray;margin-bottom: 30px;" type="password" id="id_password1" name="password1"><br>
        <label class="titulo" for="id_password2">Confirmar contraseña:</label><br>
        <input style="color:white;margin-top:10px;padding: 10px;border-radius: 20px;margin-left: 30px;background-color: rgb(30,30,30);border: solid 1px gray;margin-bottom: 30px;" type="password" id="id_password2" name="password2"><br><br>
        <button style="margin-bottom:30px;padding: 10px;border: 1px solid gray;border-radius: 20px;background-color: rgb(30,30,30);color: white;margin-left: 30px;" type="submit">Registrarse</button>
    </form>
    <p class="titulo">Ya tienes una cuenta? <a href="{% url 'pepetube:login' %}" style="color: rgb(179, 179, 179);" >Inicia Sesión</a></p>
{% endblock content %}